version: '3.8'
services:
  banco_tarefas_mssql:
    image: mcr.microsoft.com/mssql/server
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 89N8%N9RM6a5CBHj^
      MSSQL_PID: Express      
    ports:
      - "1433:1433"
    volumes:
      - "${SQL_VOLUME_PATH}:/usr/share/mssql"
    container_name: banco_tarefas_mssql
    restart: unless-stopped
    #docker-compose up -d
